<?php
$gateway_url = "https://gtw.online-epayment.com/directapi";

$env = parse_ini_file('.env');

$curlPost = array();

$protocol = isset($_SERVER["HTTPS"]) ? 'https://' : 'http://';
$source_url = $protocol . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

//<!--Your Business Public Key -->
$curlPost['public_key'] = $env["PUBLIC_KEY"];

//<!--Your Business Id -->
$curlPost['terNO'] = $env["TER_NO"];

//<!--product bill_amt,bill_currency and product name * by cart total amount -->

//<!--This is the amount to be charged from card -->
$curlPost['bill_amt'] = $_POST["bill_amt"];
//<!--This is the specified currency to charge via customer -->
$curlPost['bill_currency'] = $_POST["bill_currency"];

//<!--This is the specified Product Name to purchased. -->
$curlPost['product_name'] = $_POST["product_name"];

//<!--billing details of .* customer -->

//<!--This is the fullname of the full name or the customer -->
$curlPost['fullname'] = $_POST["fullname"];

//<!--This is the bill_email address of the customer. -->
$curlPost['bill_email'] = $_POST["bill_email"];

//<!--This is the first address of the customer. -->
$curlPost['bill_address'] = $_POST["bill_address"];

//<!--This is the city of the customer. -->
$curlPost['bill_city'] = $_POST["bill_city"];

//<!--This is the state of the customer. -->
$curlPost['bill_state'] = $_POST["bill_state"];

//<!--This is the country of the customer for ISO Alpha-2. -->
$curlPost['bill_country'] = $_POST["bill_country"];

//<!--This is the zip code of the customer. -->
$curlPost['bill_zip'] = $_POST["bill_zip"];

//<!--This is the phone number of the customer. -->
$curlPost['bill_phone'] = $_POST["bill_phone"];

//<!--This is the unique reference, unique to the particular transaction being carried out. It is generated by the merchant for every transaction -->
$curlPost['reference'] = $_POST["reference"];

//<!--webhook_url is a url you provide, we send by s2s method to it after the customer process for completes payment and append by curl the response to it as query parameters ex. https://yourdomain.com/notify.php -->
$curlPost['webhook_url'] = $_POST["webhook_url"];

//<!--return_url is a url you provide, we redirect to it after the customer completes payment and redirect this url with response to it as query parameters ex. https://yourdomain.com/success.php -->
$curlPost['return_url'] = $_POST["return_url"];

//<!--bill_ip - Internet Protocol. This represents the current IP address of the customer carrying out the transaction -->
$curlPost['bill_ip'] = $_SERVER['REMOTE_ADDR'];

//<!--source_url - Url of Product Page -->
$curlPost['source_url'] = $source_url;

//<!--default value for source and integration-type  -->
$curlPost['integration-type'] = 's2s';
$curlPost['source'] = 'Curl-Direct-Card-Payment';

//<!--card details of .* customer -->

//<!--This is the card number on the Debit/Credit card -->
$curlPost['ccno'] = $_POST["card_number"];

//<!--Card security code. This is 3/4 digit code at the back of the customers card, used for web payments. -->
$curlPost['ccvv'] = $_POST["card_cvv"];

//<!--Two-digit number representing the card's expiration month. -->
$curlPost['month'] = $_POST["card_expiry_month"];

//<!--Two-digit number representing the card's expiration year. -->
$curlPost['year'] = $_POST["card_expiry_year"];

$curl_cookie = "";
$curl = curl_init();
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);
curl_setopt($curl, CURLOPT_URL, $gateway_url);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($curl, CURLOPT_REFERER, $source_url);
curl_setopt($curl, CURLOPT_POST, 1);
curl_setopt($curl, CURLOPT_POSTFIELDS, $curlPost);
curl_setopt($curl, CURLOPT_TIMEOUT, 200);
curl_setopt($curl, CURLOPT_HEADER, 0);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_COOKIE, $curl_cookie);
$response = curl_exec($curl);

$results = json_decode($response, true);

if ((isset($results["Error"]) && ($results["Error"])) || (isset($results["error"]) && ($results["error"]))) {
	print_r($results);
	exit;
} elseif (!isset($results)) {
	echo $response;
	exit;
}


// $status_nm = (int)($results["status_nm"]);

$sub_query = http_build_query($results);

if (isset($results["authurl"]) && $results["authurl"]) {
	//3D Bank URL

	$redirecturl = $results["authurl"];
	header("Location:" . $redirecturl);
	exit;
// } elseif ($status_nm == 1 || $status_nm == 9) {
// 	// 1:Approved/Success,9:Test Transaction

// 	$redirecturl = $curlPost["success_url"];
// 	if (strpos($redirecturl, '?') !== false) {
// 		$redirecturl = $redirecturl . '&' . $sub_query;
// 	} else {
// 		$redirecturl = $redirecturl . '?' . $sub_query;
// 	}

// 	header("Location:$redirecturl");
// 	exit;
// } elseif ($status_nm == 2 || $status_nm == 22 || $status_nm == 23) {
// 	// 2:Declined/Failed, 22:Expired, 23:Cancelled


// 	$redirecturl = $curlPost["error_url"];
// 	if (strpos($redirecturl, '?') !== false) {
// 		$redirecturl = $redirecturl . '&' . $sub_query;
// 	} else {
// 		$redirecturl = $redirecturl . '?' . $sub_query;
// 	}

// 	header("Location:$redirecturl");
// 	exit;
} else {
	// Pending

	$redirecturl = $referer;
	if (strpos($redirecturl, '?') !== false) {
		$redirecturl = $redirecturl . '&' . $sub_query;
	} else {
		$redirecturl = $redirecturl . '?' . $sub_query;
	}

	header("Location:$redirecturl");
	exit;
}
